version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: fanscrm_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fanscrm
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
